### ISSUE TITLE
Which parameters can be modified to obtain more refined results?

### ISSUE THREAD

**Issue by goometasoft** [3DGS-FLoD/flod#1]
Which parameters can be modified to obtain more refined results?

**Comment by 3DGS-FLoD** [comment]
If you mean more refined results for max LoD, then you could try increasing the training iterations in "lod_iterations" for the last LoD (but it won't create a significant difference). Or you could decrease the initial scaling constraint "lod1_scaling_lower_bound" for a more refined result from the lower LoDs.
